### ISSUE TITLE
Error when connecting to Mysql RDBMS

### ISSUE THREAD

**Issue by madeesha** [wso2/analytics-solutions#182]
**Description:**
APIM analytics 2.6.0 gives following error when connecting to MYSQL (5.7) with character set utf8.

Unable to initialize table 'APIM_ReqCountAgg_HOURS': Specified key was too long; max key length is 3072 bytes
	at org.wso2.extension.siddhi.store.rdbms.RDBMSEventTable.connect(RDBMSEventTable.java:882)
	at org.wso2.siddhi.core.table.Table.connectWithRetry(Table.java:364)
	at org.wso2.siddhi.core.table.Table$1.run(Table.java:376)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.extension.siddhi.store.rdbms.exception.RDBMSTableException: Unable to initialize table 'APIM_ReqCountAgg_HOURS': Specified key was too long; max key length is 3072 bytes

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:** APIM Analytics 2.6.0

**OS, DB, other environment details and versions:**    
MYSQL 5.7 with utf8 character set.

**Steps to reproduce:**
Coonect Analytics server to MYSQL DB with utf8 character set enabled.

**Related Issues:**

**Comment by Niveathika92** [comment]
Fixed with the following PR,
https://github.com/wso2/analytics-solutions/pull/186
https://github.com/wso2/analytics-solutions/pull/187

**Comment by Niveathika92** [comment]
This is released with version 1.0.21
