### ISSUE TITLE
[EI Analytics] When selecting time span selection option, dashboard server backend throws  exception

### ISSUE THREAD

**Issue by nandika** [wso2/analytics-solutions#85]
**Description:**
 Error on '0dc4be3f-ece4-4591-94df-7fd88731c147'. Invalid input given to dateFormat(timestampInMilliseconds,dateTargetFormat) function. First argument cannot be null Exception on class 'org.wso2.extension.siddhi.execution.time.DateFormatFunctionExtension'. org.wso2.siddhi.core.exception.SiddhiAppRuntimeException: Invalid input given to dateFormat(timestampInMilliseconds,dateTargetFormat) function. First argument cannot be null
	at org.wso2.extension.siddhi.execution.time.DateFormatFunctionExtension.execute(DateFormatFunctionExtension.java:234)
	at org.wso2.siddhi.core.executor.function.FunctionExecutor.execute(FunctionExecutor.java:109)
	at org.wso2.siddhi.core.query.selector.attribute.processor.AttributeProcessor.process(AttributeProcessor.java:41)
	at org.wso2.siddhi.core.query.selector.QuerySelector.processInBatchGroupBy(QuerySelector.java:309)
	at org.wso2.siddhi.core.query.selector.QuerySelector.process(QuerySelector.java:84)
	at org.wso2.siddhi.core.query.FindStoreQueryRuntime.reset(FindStoreQueryRuntime.java:119)
	at org.wso2.siddhi.core.SiddhiAppRuntime.query(SiddhiAppRuntime.java:284)
	at org.wso2.siddhi.core.SiddhiAppRuntime.query(SiddhiAppRuntime.java:266)
	at org.wso2.carbon.data.provider.siddhi.SiddhiProvider.publish(SiddhiProvider.java:125)
	at org.wso2.carbon.data.provider.AbstractDataProvider.lambda$start$0(AbstractDataProvider.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Suggested Labels:**
EI

**Affected Product Version:**
4.3.0-Beta
**OS, DB, other environment details and versions:**    
MySQL, Linux

**Comment by Niveathika92** [comment]
@isharailanga is looking into this.. This is due to a workaround they have applied to the generated widgets.  Will be fixed after new widgets are created

**Comment by isharailanga** [comment]
Fixed in https://github.com/wso2/analytics-solutions/pull/101
